### ISSUE TITLE
ResponseSpectrum command

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#1008]
@MassimoPetracca We've reviewed the responseSpectrum command and documentation. It seems like a very nice and useful command.

It would be a better user experience to define the periods and Sa values in two lists/vectors as inputs instead of using the TimeSeries objects. It was confusing to us and took a while to figure out that the TimeSeries is what holds the Tn/Sa pairs.

The only use of the TimeSeries object is in ResponseSpectrumAnalysis::solveMode().

Another suggestion is to call this command RSA or responseSpectrumAnalysis because this command does not compute a response spectrum.

**Comment by MassimoPetracca** [comment]
@mhscott 

_It would be a better user experience to define the periods and Sa values in two lists/vectors as inputs instead of using the TimeSeries objects. It was confusing to us and took a while to figure out that the TimeSeries is what holds the Tn/Sa pairs._

Sure. You're right, I forgot to describe what the timeSeries was used for in the documentation. I can change it to use lists.

_Another suggestion is to call this command RSA or responseSpectrumAnalysis because this command does not compute a response spectrum._

Makes sense. I'll change it to responseSpectrumAnalysis

**Regarding backward compatibility**:
Do you think I should keep backward compatibility? Allowing both timeSeries and lists as input, and both responseSpectrum and responseSpectrumAnalysis as command name?
Or should I just go with the new format?

I'll wait for your answer and then I will make a PR

**Comment by mhscott** [comment]
@MassimoPetracca Thanks! I think the command is new enough that you can change the name to `RSA` and/or `responseSpectrumAnalysis` and free up `responseSpectrum` for a command that computes a response spectrum (not planned, and probably not needed as making a spectrum is easily scripted)

**Comment by MassimoPetracca** [comment]
@mhscott done here #1011
