### ISSUE TITLE
recorder showing zero values when using MultipleSupport command in OpenSees 3.5.0

### ISSUE THREAD

**Issue by mtsonicc** [OpenSees/OpenSees#1252]
The node recorder shows zero values when using 
MultipleSupport along with imposedMotion (or imposedSupportMotion) command in OpenSees 3.5.0.

It worked fine when I use OpenSees 3.4.0.

Tested environment: Ubuntu 22 (Intel CPU), macOS 13.4.1 (Apple M1)

**Comment by mtsonicc** [comment]
It seems that `set lambdaI [eigen -fullGenLapack 1]` is causing the problem.
This line used to have no issue when using OpenSees 3.4.0 or lower.

```
model BasicBuilder -ndm 1 -ndf 1;
node  1   0.
node  2   1.
fix   1   1;
mass 2 3
uniaxialMaterial  Elastic 11 100.
element Truss 1   1 2    1.0 11
recorder Node -file dAbs2.out -node 2 -dof 1 disp;
recorder Node -file vAbs2.out -node 2 -dof 1 vel;
recorder Node -file aAbs2.out -node 2 -dof 1 accel;
constraints Transformation;
numberer RCM;
system BandGeneral;
test NormUnbalance 1.e-10 500   0;
algorithm KrylovNewton;
algorithm ModifiedNewton;
integrator Newmark 0.5 0.25
analysis Transient;

set lambdaI [eigen -fullGenLapack 1]

pattern MultipleSupport 400 {
    set DispSeries "Sine 0. 20. 1."
    groundMotion 999 Plain -accel  $DispSeries
    imposedMotion 1     1    999
}
set ok [analyze 100 0.01 ]
```

**Comment by mhscott** [comment]
Thanks for providing the example.

If you put the eigen command before the analysis options, it works fine. It also works fine as-is with UniformExcitation instead of MultiSupport. Must be something with the constraints imposed by the MultiSupport pattern.

**Comment by fmckenna** [comment]
not really a bug this one .. the node has been fixed and then the ground motion imposed .. thus there are two constraints set on node .. if using imposed constraints you need to remove the constraint after the eigen before adding it in the ground motion command .. otherwise the results are going to be undetermined in sense that depending on constraint handler and subsequent analysis options you will get different results as I do not check for multiple conflicting constraints.

the end of file should look like the following:

set lambdaI [eigen -fullGenLapack 1]

remove sp 1 1

pattern MultipleSupport 400 {
    set DispSeries "Sine 0. 20. .1"
    groundMotion 999 Plain -accel  $DispSeries
    imposedMotion 1     1    999
}
set ok [analyze 100 0.01]
