### ISSUE TITLE
initDisp in Tetrahedral elements

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#1331]
@jaabell Setting initDisp in `setDomain` breaks `sendSelf` and `recvSelf`. This behavior should be optional, based on user input to FourNodeTetrahedron and TenNodeTetrahedron

**Comment by jaabell** [comment]
Hi Michael. Good point. I'll look into it.

**Comment by mhscott** [comment]
Any updates?

**Comment by jaabell** [comment]
Here is a little test. It consists of a stack of tetrahedral elements analyzed in two stages, one for each "level" with 3 tets each. The first stage of elements has body foces, then the second level of tets is added without body forces. 

If doInitDisp is off (default) the second stage alters the displacements of the first stage because the element will not consider the initial deformed geometry. If the flag is set to true, then the second stage considers the initial displacements of the nodes in the first stage and subtracts them before computing the strains sent to the gauss points. This results in the second stage (which adds no more load) not changing the displacements at all. 

`
import opensees as ops

doInitDisp = True

ops.wipe()
ops.model('basic','-ndm',3,'-ndf',3)

ops.node(1,0,0,0); ops.fix(1,1,1,1)
ops.node(2,1,0,0); ops.fix(2,1,1,1)
ops.node(3,1,1,0); ops.fix(3,1,1,1)
ops.node(4,0,0,1)
ops.node(5,1,0,1)
ops.node(6,1,1,1)

matTag  = 1
ops.nDMaterial("ElasticIsotropic3D", matTag , 100, 0.25)

ops.element("FourNodeTetrahedron", 1, 1, 2, 3, 4, matTag, 0, 0, -1)
ops.element("FourNodeTetrahedron", 2, 2, 3, 4, 5, matTag, 0, 0, -1)
ops.element("FourNodeTetrahedron", 3, 4, 5, 6, 3, matTag, 0, 0, -1)

ops.system('UmfPack')
ops.analysis('Static','-noWarnings')
ops.analyze(1)


print("Displacements first stage")
for nd in ops.getNodeTags():
    print(f"{nd} : {ops.nodeDisp(nd)}")

ops.node(7,0,0,2)
ops.node(8,1,0,2)
ops.node(9,1,1,2)

ops.element("FourNodeTetrahedron", 4, 4, 5, 6, 7, matTag, 0, 0, 0, doInitDisp)
ops.element("FourNodeTetrahedron", 5, 7, 5, 6, 8, matTag, 0, 0, 0, doInitDisp)
ops.element("FourNodeTetrahedron", 6, 7, 8, 9, 6, matTag, 0, 0, 0, doInitDisp)

ops.system('UmfPack')
ops.analysis('Static','-noWarnings')
ops.analyze(1)

print("Displacements second stage")
for nd in ops.getNodeTags():
    print(f"{nd} : {ops.nodeDisp(nd)}")
` 

Result if doInitDisp = False

`Displacements first stage
1 : [0.0, 0.0, 0.0]
2 : [0.0, 0.0, 0.0]
3 : [0.0, 0.0, 0.0]
4 : [0.0005000000000000004, -0.0004999999999999998, -0.00225]
5 : [-0.005460098379629629, -0.0009149016203703705, 0.0026249999999999993]
6 : [-0.0049600983796296285, 0.0017100983796296293, -0.0005000000000000003]
Displacements second stage
1 : [0.0, 0.0, 0.0]
2 : [0.0, 0.0, 0.0]
3 : [0.0, 0.0, 0.0]
4 : [0.00011467889908257348, 0.002733180428134559, -0.0021215596330275226]
5 : [-0.0010607798165137546, 0.007157874617737014, -0.002866972477064231]
6 : [-0.0009461009174311832, 0.014439984709480151, -0.007415902140672797]
7 : [0.002551605504587176, 0.005590596330275229, -0.004720948012232422]
8 : [-0.0029537670458737115, -0.0034586947278265976, 0.002723623853211006]
9 : [-0.0011475743853232483, 0.002131901602448642, -0.001825305810397557]`

Results if `doInitDisp=True`:
`Displacements first stage
1 : [0.0, 0.0, 0.0]
2 : [0.0, 0.0, 0.0]
3 : [0.0, 0.0, 0.0]
4 : [0.0005000000000000004, -0.0004999999999999998, -0.00225]
5 : [-0.005460098379629629, -0.0009149016203703705, 0.0026249999999999993]
6 : [-0.0049600983796296285, 0.0017100983796296293, -0.0005000000000000003]
Displacements second stage
1 : [0.0, 0.0, 0.0]
2 : [0.0, 0.0, 0.0]
3 : [0.0, 0.0, 0.0]
4 : [0.0005, -0.0004999999999999993, -0.00225]
5 : [-0.005460098379629629, -0.0009149016203703688, 0.0026249999999999993]
6 : [-0.004960098379629629, 0.0017100983796296324, -0.0005000000000000012]
7 : [-3.8658272874907326e-19, 1.1305045680168844e-18, -8.556245034605805e-19]
8 : [-1.3323888311439137e-18, 1.5031005886705304e-19, 1.0515766392217228e-18]
9 : [-1.445782452853405e-18, 1.1181843010111114e-18, 7.286037535280989e-20]
`
