### ISSUE TITLE
Problem with node numbering and associated mass while using the equalDOF/rigidLink command

### ISSUE THREAD

**Issue by mgrubisic** [OpenSees/OpenSees#1443]
This problem involves **sequentially constrained nodes using the equalDOF/rigidLink** command.

An issue was identified through a MWE showing that an unconventional node numbering sequence **disrupts the proper linkage of master and slave nodes' masses** when using the equalDOF or rigidLink commands. This discrepancy is evident from the modal characteristics compared to a model with straightforward node numbering.

The inconsistency is observed with both the eigen and modalProperties commands and affects transient analysis responses. The MWE demonstrates this issue with three problematic node numbering sequences, each yielding different results in 1D, 2D, and 3D scenarios, as detailed in the accompanying files.

A recurring observation from the examples is that if the tag of the last constrained/secondary node in a sequence is smaller than the tag of the corresponding retained/primary node, **the mass of the constrained/secondary node is excluded from the model when using the equalDOF or rigidLink command**, even though the constrained nodes have the expected displacements.

This MWE has been tested on Windows and Linux systems using the latest OpenSeesPy 3.5.1.12.

The MWE files can be found on the following link:
**https://github.com/mgrubisic/OpenSees_Public_Tests**

**Comment by MassimoPetracca** [comment]
@mgrubisic It happens because you are not following the rules of retained/constrained nodes layout for the Transformation constraint handler.

- A node/DOF that is constrained in an MP constraint cannot be a retained node in another MP constraint
- Do not impose an SP constraint on a node that is constrained in an MP constraint.

Here, for example, node 3 is constrained in the first MP constraint but retained in the third MP constraint.
The Transformation handler tries to remove (transform) the equation for the constrained DOF making it a function of the retained DOF. When this constrained equation (eliminated) is to be used as a retained equation in the second MP constraint, it won't be found, thus the second constraint will not be imposed.
Depending on the node numbering either the first or the second constraint will be skipped.
```python
ops.equalDOF(node2, node3, 1) # Nodes 2 & 3
ops.equalDOF(node2, node5, 1) # Nodes 2 & 5
    
ops.equalDOF(node3, node4, 1) # Nodes 3 & 4
ops.equalDOF(node5, node6, 1) # Nodes 5 & 6
```

As an example, try this wrapper function that takes the trial retained node as an argument. It will check whether that node is already constrained somewhere else, and, if so, it will return the node of the its retained node in the previous constraint.

```python
def _VR(node):
    # let's see if this retained node is a constrained node
    # in another constraint. if so, return its retained node in the existing
    # constraint
    already_retained = ops.getRetainedNodes(node)
    if len(already_retained) == 0:
        return node
    else:
        print('Warning. retained node {} is already constrained to node {}'.format(node, already_retained))
        return already_retained[0]

ops.equalDOF(_VR(node2), node3, 1) # Nodes 2 & 3
ops.equalDOF(_VR(node2), node5, 1) # Nodes 2 & 5

ops.equalDOF(_VR(node3), node4, 1) # Nodes 3 & 4
ops.equalDOF(_VR(node5), node6, 1) # Nodes 5 & 6
```
if you run your "problematic" example you will see these warnings, and the results will be correct:
```
Warning. retained node 3 is already constrained to node [2]
Warning. retained node 5 is already constrained to node [2]
```

**NOTE**: Don't use this function as a working utility. It's just an example. To properly check the retained-constrained layout you should also check the DOFs, not only the nodes!
