### ISSUE TITLE
An error occurred in debug mode: in debug mode ArpackSolver (default eigensolver) got error

### ISSUE THREAD

**Issue by HaoxinGuo** [OpenSees/OpenSees#148]
## An error in debug mode
An error occurred while  running the following code
```tcl
set xDamp 0.05;
set nEigenI 1;
set nEigenJ 2;
set lambdaN [eigen [expr $nEigenJ]]; # the error happend
set lambdaI [lindex $lambdaN [expr $nEigenI-1]];
set lambdaJ [lindex $lambdaN [expr $nEigenJ-1]];
``` 
And the error is shown in this figure 
![error](https://user-images.githubusercontent.com/41227936/66312667-ab728300-e943-11e9-9aab-75c9555ca947.png)
However **it's going well in release mode.**
## The reason I summed up
**in debug mode ArpackSolver (default eigensolver) got error** 
use release version  work me fine
It is also possible that I have some errors while compiling.
## source tcl code 
[source_tcl_code.zip](https://github.com/OpenSees/OpenSees/files/3697413/source_tcl_code.zip)

**Comment by mhscott** [comment]
Do you get the same error if you ask for fewer eigenvalues from the 'eigen' command?

**Comment by HaoxinGuo** [comment]
Yes, I got the same error. It didn't work when I use the command ```eigen 1``` or ```set lambda [eigen 1 ];```
Thanks a lot

**Comment by erikemondt** [comment]
Dear Haoxin,

did you resolve this error?  I'm facing the same problem. I followed the steps described by Han H. here: https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/520507.
This changed the error from the one you show to the eigenvalue becoming a ridiculously large number. I don't know if the steps provided in this link are part of the solution, or a wrong approach. For me the error shows both in debug and release mode. If this is not the case, my guess would be that the problem is somewhere in the project settings. Check these for differences between debug and release.

**Comment by mhscott** [comment]
Closing old issues.  Thank our @erikemondt for the fix.  If this did not work @HaoxinGuo, please start a new issue.
