### ISSUE TITLE
Clarification on ElasticPPcpp file regarding adding material to OpenSees

### ISSUE THREAD

**Issue by benjaminsoraghi** [OpenSees/OpenSees#177]
Hello

I was recently learning how to add new material to OpenSees. I followed Dr. McKenna's instructions and I was successful to build and compile it to get the _.dll_ and/or _OpenSess.exe_ file. My question here is about the concept of the _ElasticPPcpp_ file(s). 
I initially thought that the _ElasticPPcpp_ file is the exact copy of _Elastic-Perfectly Plastic Material_ written in cpp (C++), but just a different name to teach us how to add a material source code written in C++ to OpenSees using Visual Studio. However, as I was comparing the _ElasticPPcpp_ file with _ElasticMaterial_ and/or _ElasticPPMaterial_ that already exists in the OpenSees library I found them slightly different. 
I do appreciate that you explain where exactly this _ElastipPPcpp_ file come from?
The reason I am asking this question is that as Dr. McKenna mentioned, we should start from an existing file and change it based on the new material we are going to add.

Thank you
Benjamin

**Comment by ahartloper** [comment]
1. What is your objective? I assume you would like to create a new material in OpenSees?
2. Are you familiar with object-oriented programming?

**Comment by benjaminsoraghi** [comment]
@ahartloper Thanks for your reply.
1. I need to add new concrete material to OpenSees (using monotonic and cyclic laboratory results)
2. I am guessing object-oriented programming is when we just need to change a piece of larger code that concerns our objective!

**Comment by ahartloper** [comment]
I would start by reading this: https://doi.org/10.1061/(ASCE)CP.1943-5487.0000002

Essentially your new material is a subclass of the UniaxialMaterial (or NDMaterial). This new class needs to implement methods (functions) that are defined by the virtual methods in the UniaxialMaterial class (or NDMaterial).

Any valid OpenSees material should define these methods, so in principle it doesn't matter which material you use as a starting point. I can suggest the  [UVCuniaxial material](https://github.com/OpenSees/OpenSees/blob/master/SRC/material/uniaxial/UVCuniaxial.h) since I wrote this in the way that made the most sense to me, but any other material should be fine.

**Comment by mhscott** [comment]
If you want to drill down to elements and materials, read this one too:
http://dx.doi.org/10.1061/(ASCE)0733-9445(2008)134:4(562)

**Comment by mhscott** [comment]
Closing old issues. If issues remain, please start a new thread.
