### ISSUE TITLE
Warning while using fiber section command without -GJ in macOS

### ISSUE THREAD

**Issue by HHangLi** [OpenSees/OpenSees#190]
I ran OpenSees in macOS Catalina.
In OpenSees v3.0.3 the tcl file ran successfully.
However,  the same file returned following warning and cannot run any further when I upgraded to v3.1.0:

```
WARNING - no torsion specified for 3D fiber section, use -GJ or -torsion

FiberSection3d: 1112
```

The error occurred when the command `section Fiber $secTag {...}` executed.
After reformatting the command into `section Fiber $secTag -GJ 0. {...}`, the tcl file works again and obtains the same result as v3.0.3.

Is this a bug needed to be fixed? Or will the document change the `-GJ` argument to non-optional in the future?

**Comment by mhscott** [comment]
Thank you for pointing this out.  We will update the documentation.  The issue is a recent change described here: https://wp.me/pbejzW-9X

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://cce.oregonstate.edu/scott>
OpenSees blog: portwooddigital.com<http://www.portwooddigital.com/>
________________________________
