### ISSUE TITLE
More downstream support for OpenSees

### ISSUE THREAD

**Issue by luzpaz** [OpenSees/OpenSees#248]
Currently it seems OpenSees is only available for Arch Linux (and at the time of writing this, the version is outdated (v2.5)).

[![Packaging status](https://repology.org/badge/vertical-allrepos/opensees.svg?header=OpenSees)](https://repology.org/project/opensees/versions)

Perhaps the community can start making efforts to get the OpenSees packaged in more mainstream distros like, Debian, Ubuntu, OpenSUSE, Fedora, Conda, Homebrew etc...?

**Comment by luzpaz** [comment]
Note: recently an unofficial OpenSees package was shared on https://forum.freecadweb.org/viewtopic.php?f=18&t=20745&p=371448#p371374 for Ubuntu/Debian

**Comment by kkremitzki** [comment]
I would be interested in possibly packaging/maintaining OpenSees for Debian as part of the Debian Science Team, but right now it's not possible for it to be included in Debian proper because of the noncommercial/internal-only clause in the license, which doesn't meet the Debian Free Software Guidelines or the [Open Source Initiative's definition of open source](https://opensource.org/osd).

A change of license by the copyright holder(s) would be the only option, which is understandably difficult, but there are several options to choose from based on the project's goals if that were to be considered: https://wiki.debian.org/DFSGLicenses

**Comment by GJoe2** [comment]
Now ArchLinux has lost his first citizen status, no AUR packages neither a MAKE file in upstream. I tried compiling from someone else [makepkg](https://github.com/nemaarpit/OpenSees_Linux/tree/main/Arch_User_Repository) , but at some point failed.
