### ISSUE TITLE
OpenSees (Model question)

### ISSUE THREAD

**Issue by Ray220** [OpenSees/OpenSees#272]
OPENSEES IMPLEMENTATION:
The OpenSees administration provides a list of prototype examples showing ways of modelling the structural elements. I would like to use the concentrated plasticity approach to simulate the nonlinear response of frame structural elements. This approach assumes that inelastic behavior is concentrated at the ends of elements and the member elements behave in a linear-elastic mode in the region between the two-end hinges as shown in Figure. The rotational springs which is representing the region of concentrated plasticity follow a bilinear hysteretic response based on the Modified Ibarra Krawinkler Deterioration Model which is used to represent the element stiffness. 
 
An example is listed in the OpenSees web page explaining the way how to implement this approach into Opensees model. This model adds one node at zero length from the main nodes to connect the zero-length spring which is used to represent the plasticity of the elements. As a result, the connections between the structural elements are modelled separately. Modelling the connections separately is useful in steel structures in order to capture connection flexibility and panel zone displacement. However, my study case is concerned with reinforced concrete building. 
My questions are: 
1.	Do I need to keep these zero-length nodes?
2.	Do I need to calculate the data for the rotational spring response parameters in the light of the Modified Ibarra Krawinkler Deterioration Model? or calculate the data of response parameters based on moment-rotation relationships of the member. 
Note: the prototype example uses command “rotSpring2DModIKModel.tcl” to insert the rotational springs data.

**Comment by zhuminjie** [comment]
There is no figure shown. Can you post the figure here?

**Comment by Ray220** [comment]
Sent from Mail for Windows 10

**Comment by zhuminjie** [comment]
Can you post the figure here?

**Comment by Ray220** [comment]
For some reason I cannot add the figure here, but, I can summarize the figure as follow:

========o@o@o========

- the equal sign is the elastic element 
- the o sign is the nodes
- the @ sign is the rotation springs

**Comment by u-anurag** [comment]
PS: Just copy the figure and paste it in the comment box to add it. (If you are not doing it already)

If you want to use a concentrated plasticity model, you will have to keep the zero-length springs at the end of the elements., hence keep the nodes. You can use any material model to represent the plastic hinge behavior. But MIK Damage Model is developed to represent that because of pinching involved. If using the MIK model, I would recommend calculating the parameters using that specific procedure. You can see this published article by [Wu and Pantelides (2018)](https://www.researchgate.net/publication/327039791_Concentrated_and_Distributed_Plasticity_Models_for_Seismic_Repair_of_Damaged_RC_Bridge_Columns). 

Another approach would be to use [BeamWithHinges](https://openseespydoc.readthedocs.io/en/latest/src/beamWithHinges.html) element. That will eliminate the need for extra nodes unless you are dealing with bar-slip or other localized behavior.

**Comment by Ray220** [comment]
Sorry I still cannot post te figure, but it is in this link. thank you
https://opensees.berkeley.edu/wiki/index.php/File:2s1b-Sketch.PNG
