### ISSUE TITLE
Creation of DLL failed

### ISSUE THREAD

**Issue by talledodiego** [OpenSees/OpenSees#34]
I created a DLL with Visual Studio 2017.
Compiling error C1083: impossible to open file bool.h

the include is in EigenSOE.h in the core directory:

#ifndef _bool_h
#include <bool.h>
#endif

**Comment by essi87** [comment]
Hi, I had the same problem. Just add the bool.h file (available in SRC) to your project in visual studio.

**Comment by talledodiego** [comment]
Thank you. Alternatively you could use stdbool  from standar library.
I solved the problem, but the repository should be updated including the file book in the core folder for future use .

Best regards

Diego

Inviato da iPhone

__________________________________
Università Iuav di Venezia
__________________________________
ing. Diego Alejandro Talledo
Terese - Dorsoduro 2206 - I 30123 Venezia
diego.talledo@iuav.it
tel +39 3405315225
fax +39 0445 372414 
www.iuav.it
__________________________________



Sostieni la ricerca: scegli l’Università Iuav di Venezia
Destinare il cinque per mille alla ricerca universitaria è importante.
Non costa nulla e non è una scelta alternativa all’8 per mille.
Firma nello spazio finanziamento della ricerca scientifica e dell’Università 
e indica il codice fiscale dell’Università Iuav di Venezia 80009280274

**Comment by essi87** [comment]
Hi Diego, 
I have made the .dll for my material. However, when I run an example, it gives me this error: it could not create the uniaxial material. Did you have the same problem? if yes, how did you solve it?

Ehsan,

**Comment by talledodiego** [comment]
In my case it worked fine.
I have a dll of a uniaxial material that is fully working.
Can you be more specific about the error? Did you included the dll in a path that could be find by your Opensees?

Inviato da iPhone

__________________________________
Università Iuav di Venezia
__________________________________
ing. Diego Alejandro Talledo
Terese - Dorsoduro 2206 - I 30123 Venezia
diego.talledo@iuav.it
tel +39 3405315225
fax +39 0445 372414 
www.iuav.it
__________________________________



Sostieni la ricerca: scegli l’Università Iuav di Venezia
Destinare il cinque per mille alla ricerca universitaria è importante.
Non costa nulla e non è una scelta alternativa all’8 per mille.
Firma nello spazio finanziamento della ricerca scientifica e dell’Università 
e indica il codice fiscale dell’Università Iuav di Venezia 80009280274

**Comment by essi87** [comment]
Thanks for your quick reply. I put the .dll file in same path as my .h and .cpp files. The path is: ''D:\Opensees_code\DEVELOPER\material\cpp'' which includes .h, .cpp, .dll, Opensees.exe, and example.tcl files. When I run it, it gives me this error: 
WARNING could not create uniaxialMaterial MetalRubber 
    while executing 
"uniaxialMaterial MetalRubber 1 $Pmr $Pw $e $Db $Dw $a $b $zeta $lambda          	# build rubber metal material"  

It basically starts reading the example.tcl file and wheN it reaches the new material creation, it cannot create it. Is path fine or am I missing something? I appreciate your help on this.

Thanks,
Ehsan

**Comment by essi87** [comment]
Hi Diego, I would like to try your method as well . Could please tell me what you mean by "you could use stdbool  from standar library" and explain a bit more.

Many thanks,
Ehsan

**Comment by essi87** [comment]
Hi Diego,
Many thanks for your comment. When I create the .dll file for the ElasticPP
example presented in the opensees tutorial for adding new material, I still
get the same error. I reckon it might be the version of opensees I am
using. As you said you have recently implemented a new material in Opensees
and it works nicely, Is that possible for you to send me a working example
of the ElasticPP example including all required files and folders
(Opensees.exe, Developer, and etc) which can allow me to check if I am
missing any file?

Highly appreciate your help on this,

Ehsan,

**Comment by talledodiego** [comment]
I insist the problem should be the path.
Do a very simple test: opensees.exe your dll and tcl files in the same folder. Run the script.

**Comment by benjaminsoraghi** [comment]
Thank you for explaining how to fix the _bool.h_ problem as I have it with Visual Studio 2010. As I read your comments it seems that with Visual Studio 2017 the problem should be solved. However, I do NOT know how to create the _.dll_ file using the SV 2017 since it is different than VS 2010.
I am following steps from [Frank McKenna](https://opensees.berkeley.edu/OpenSees/workshops/OpenSeesDays2012/B3_AddingYourCode.pdf) Instruction to build the _ElasticPPcpp_ file.
Could you please help me with the procedure in building the _.dll_ file in Visual Studio 2017?

Thank you very much

**Comment by Nigel-7** [comment]
Hello, thank you for bringing up this issue. I also encountered problems when adding the example ElasticPPcpp material to opensees. I am using Visual Studio 2017 to create the dll file and I followed every step illustrated by Dr. Frank. Here is the screenshot of the error I got. Anyone know what the problem is? Your help is greatly appreciated!
<img width="704" alt="Errors" src="https://user-images.githubusercontent.com/59978531/72575436-604d0200-389a-11ea-8c05-96ac0619bb09.png">

**Comment by Nigel-7** [comment]
Hello all, thank you for sharing your experience. I am also using Visual Studio 2017 to try to add new material to opensees. I tried to follow every step illustrated by Frank McKenna, but not sure if what I did was right since Visual Studio 2017 seems a lot different from Visual Studio 2010. I fixed the bool.h problem as you instructed. In the end I still can not work it out, still got errors shown in the figure. Any help would be highly appreciated.
<img width="704" alt="Errors" src="https://user-images.githubusercontent.com/59978531/72584275-74ebc300-38b7-11ea-9bc8-ce58328afdf1.png">

**Comment by erikemondt** [comment]
Hi Nigel-7

I patched the second LNK 2019 error by commenting out the line in the code that caused the error. This line only prints some model information to a .json file, which is not used as input somewhere else. It appears to be for debugging purposes and is not used by OpenSees under normal circumstances.

Go to the following file:
\DEVELOPER\core\Domain.cpp (or access it in the source files of visual studio)
comment out this line: "OPS_printCrdTransf(s, flag);"

It's wise to insert an additional print statement here, denoting that code was commented out.
It would be even better to debug the OPS-printCrdTransf() function there instead of commenting it out

**Comment by prafulla-malla** [comment]
![image](https://user-images.githubusercontent.com/34392453/95845563-0ebe9e80-0d6a-11eb-9361-ac2cd32a4174.png)
How can I solve this problem while creating .dll file with VS2019

**Comment by mhscott** [comment]
We are going to remove the DLL stuff and will make videos on how to add elements and material to OpenSees without DLLs, which cause too many problems.
