### ISSUE TITLE
Error in compiling opesees.exe with vs2019

### ISSUE THREAD

**Issue by prafulla-malla** [OpenSees/OpenSees#457]
I am getting this error while trying to build opensees.exe
![image](https://user-images.githubusercontent.com/34392453/95974709-0c754680-0e35-11eb-93cd-df9a4a5bafd1.png)
![image](https://user-images.githubusercontent.com/34392453/95974923-41819900-0e35-11eb-96ce-3c9fd60bb050.png)

**Comment by csasj** [comment]
The warning LNK4075 doesn't affect to OpenSees compilation. I've the same warning and I'm able to compile it successfully. 

Your problem seems to be related with the second issue shown in your screenshot, the actor project is not compiling. 
1. There were some compilation issues that have been corrected recently. Be sure that you've pulled the last commit. 
2. If suggestion 1) not worked, try to find the error that causes that the compilation of _actor_ project fails (eg. C1083 error or  LNK2019 error).

**Comment by mhscott** [comment]
Has this been resolved? There have been updates to the Visual Studio projects that may help with this issue.

**Comment by mhscott** [comment]
Closing this issue. If problems remain, please start a new issue.
