### ISSUE TITLE
Error in compiling opesees.exe with vs2019

### ISSUE THREAD

**Issue by maheshbabuaddala** [OpenSees/OpenSees#489]
getRayleighDampingForce method declined access in all modulus

**Comment by mhscott** [comment]
https://www.youtube.com/watch?v=BLcY1w7a5Ec

Go to about 20:00, the issue is addressed there.



--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
o: 1-541-737-6996
OpenSees blog: www.portwooddigital.com<https://outlook.office.com/mail/options/mail/messageContent/www.portwooddigital.com>
________________________________
