### ISSUE TITLE
QuadMesh Generator not working

### ISSUE THREAD

**Issue by gaaraujo** [OpenSees/OpenSees#643]
Hello,
I am trying to use the Quad Mesh generator from OpenSees but I get the error in Image 1. Nodes and lines are created as in Image 2. Note that bottom_line and right_line share node 7 and thus should be connected. When I look into the source code from QuadGenerator (https://github.com/.../PFEMElement/QuadMeshGenerator.cpp), I notice that it checks that the last node in line[0] is the first node in line[1], along with some other variations (Image 3). Is there any chance the nodes in the line[0], line[1],... arrays in C++ are sorted differently than the order used to create the line mesh? For example, if I use ops.getNodeTags('-mesh', left_line), I get the output in Image 4. I would have expected the order of the tags to be according to coordinates (8, 55, 56, 57, 1). Maybe the node tags are stored in this order in the line array and that is why QuadMesh is not working? Or is there something I am missing?
Image 1:
![image](https://user-images.githubusercontent.com/24374005/129124317-a948e311-01f5-4385-a369-93709ddead8c.png)

Image 2:
![image](https://user-images.githubusercontent.com/24374005/129124359-3eb5778c-6386-4e6b-bdfe-83ec9b83fb6f.png)

Image 3:
![image](https://user-images.githubusercontent.com/24374005/129124549-f95254b1-2d61-4709-af85-57e53f0eebe5.png)

Image 4:
![image](https://user-images.githubusercontent.com/24374005/129124568-78b48f4a-2650-4a3c-b587-c65e6e404a8a.png)

**Comment by mhscott** [comment]
What are your values of a, L, and D?


From: Gustavo Araujo Rodriguez ***@***.***>
Sent: Wednesday, August 11, 2021 6:37 PM
To: OpenSees/OpenSees ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenSees/OpenSees] QuadMesh Generator not working (#643)


[This email originated from outside of OSU. Use caution with links and attachments.]

Hello,
I am trying to use the Quad Mesh generator from OpenSees but I get the error in Image 1. Nodes and lines are created as in Image 2. Note that bottom_line and right_line share node 7 and thus should be connected. When I look into the source code from QuadGenerator (https://github.com/.../PFEMElement/QuadMeshGenerator.cpp<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F...%2FPFEMElement%2FQuadMeshGenerator.cpp&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075549270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LYTXwyosX9azo90dG4uTyLWKAIQ9ljzuQY7RZ24%2Fu38%3D&reserved=0>), I notice that it checks that the last node in line[0] is the first node in line[1], along with some other variations (Image 3). Is there any chance the nodes in the line[0], line[1],... arrays in C++ are sorted differently than the order used to create the line mesh? For example, if I use ops.getNodeTags('-mesh', left_line), I get the output in Image 4. I would have expected the order of the tags to be according to coordinates (8, 55, 56, 57, 1). Maybe the node tags are stored in this order in the line array and that is why QuadMesh is not working? Or is there something I am missing?
Image 1:
[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F24374005%2F129124317-a948e311-01f5-4385-a369-93709ddead8c.png&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075549270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pgm24Mtyg08qRriEX%2BgzbBz2mHOjCnHmK345AWjQwf0%3D&reserved=0>

Image 2:
[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F24374005%2F129124359-3eb5778c-6386-4e6b-bdfe-83ec9b83fb6f.png&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075559258%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FzB2AsLEAfK1ipvGX2x7m67sKKfIZ5gmq%2Flu%2BlM6hFo%3D&reserved=0>

Image 3:
[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F24374005%2F129124549-f95254b1-2d61-4709-af85-57e53f0eebe5.png&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075559258%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yJEEaGwfFE0wN75l68UzwvjTZ%2BS2JAnGraD77jxikPQ%3D&reserved=0>

Image 4:
[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F24374005%2F129124568-78b48f4a-2650-4a3c-b587-c65e6e404a8a.png&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075569250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fad10qPH1l5GPwuVhAjK8QCJoU6dIywL88sF7F26CzA%3D&reserved=0>

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenSees%2FOpenSees%2Fissues%2F643&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075579250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j71EBrvt2ugh7bFau674rvJm6wTaxOX3x6z19d3dhG0%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADEIU7H5CXXJHUQDLUTGECTT4MQS3ANCNFSM5B75EILQ&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075579250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2KTn9VgzqTnY3DY7dGOnlsMzrUZJawmHB%2FBx2T78R%2Bc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075589237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vRsV%2B2ZtAJhRFHWcmjpgP3JGNNBXKon59wUB9K4tNzQ%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.scott%40oregonstate.edu%7C20d3e67018654314b5e008d95d31a593%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637643290075589237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ot6a74DuyjA0a7q10y7d9WgbigL7BbmEyfOw%2FSRZCMY%3D&reserved=0>.

**Comment by zhuminjie** [comment]
I think the problem is that for the quad mesh all four lines must be straight lines. Your bottom and top lines have more than 2 points, which are not guaranteed as straight lines. Changing them to 2 points should fix it.
