### ISSUE TITLE
Element::getCharacteristicLength

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#647]
This is an old method, but it's not called by any class implementation. The method should be removed and you can use recorders or something else. 'grep getCharacteristicLength -r .' in OpenSees/SRC returns occurrences in only Element.h and Element.cpp

@MassimoPetracca I see you made a bug fix in March 2020, so am I missing anything? What were you fixing if this method is not called?

**Comment by MassimoPetracca** [comment]
Dear @mhscott, we were using it for a plastic-damage model that is currently under testing, and we use it to perform an automatic fracture energy regularization based on the active element's characteristic length.

We will add soon a series of "template" continuum-damage and plastic 3d models that will use that method if the user chooses a softening uniaxial law.

If you wish to remove it, because it's a method that is too specialized, can I added it back to the Element class in the setResponse method in a new PR?

**Comment by mhscott** [comment]
It's not general, but probably OK to leave it in the interface if it's going to be used.

**Comment by talledodiego** [comment]
The method was originally added by Frank helping us for fracture energy regularisation. We also still use it in our material model.

**Comment by mhscott** [comment]
I look forward to when you merge the material models so others can use it. The method has been there for several years, so I'm not sure what you're waiting for. Right now, the method is unused in OpenSees:master and unnecessarily bloating everyone else's fork.
