### ISSUE TITLE
Getting Geometric transform Tag

### ISSUE THREAD

**Issue by BijanSeif** [OpenSees/OpenSees#696]
Hi

In Opensees, As you know there are commands that give us list of the elements and nodes TAG. Is there any command that gives us the list of the generated geometric-transformation TAGS?

With Best Regards,
Bijan

**Comment by jaabell** [comment]
I'm sorry I didn't document the changes. You can take a look at the commit diffs and let me know if you have any questions. Basically two steps:

1. Add the functionality for building the object tag list to the CrdTransf class.
2. Create a new command in commands.cpp so that TCL can invoke the new functionality and do something with it.

**Comment by BijanSeif** [comment]
Thanks dear Prof. **@jaabell**
I'm doing what you said if I encounter with any problem I will ask you again. 

Thanks again
With Best Regards,
@BijanSeif

**Comment by mhscott** [comment]
@BijanSeif Don't you want this for Python? https://github.com/OpenSees/OpenSees/pull/710

**Comment by BijanSeif** [comment]
> @BijanSeif Don't you want this for Python? https://github.com/OpenSees/OpenSees/pull/710

Hi Prof.  @mhscott 
I thought that I have to wait for next release of opensees and after that wait for openseespy release. Is there any other way to have it in python?!!!. 

Honesty YES I need it for Python and it is so helpful for me. And also it is so interesting to know the structure of developing Openseespy if it is possible!!!

Thank you Prof. **@mhscott**.
