### ISSUE TITLE
InitialStateAnalysis - MPI_Channel::recvID() - incorrect number of entries for ID received

### ISSUE THREAD

**Issue by mfernba** [OpenSees/OpenSees#701]
hi @mfernba:
 I noticed that in your model "shearbeam.tcl", there is no initial state analysis, i.e. the InitialStateAnalysis command, when I use teh InitialStateAnalysis command to analysis a large model, the analysis was failed due to error as follow:
"MPI_Channel::recvID() - incorrect number of entries for ID received: 1 exptected: 4
ShadowSubdomain::revertToStart ERROR ERROR"
I want to know that have you ever seen the error, and did you fix it?
much thanks.

_Originally posted by @Chenshupei95 in https://github.com/OpenSees/OpenSees/issues/596#issuecomment-955203613_

**Comment by mfernba** [comment]
@Chenshupei95 send me a .tcl which raises the error and I'll try to look at it as soon as possible (too busy and not in OpenSees related tasks right now).

**Comment by Chenshupei95** [comment]
Thank you very much for your reply, the attached file is my OpenSees model which raises this error, the OpenSees version I used is OpenSeesSP , v 2.5.0,  windows 64 bit. Thank you again for your reply.













At 2021-11-02 01:06:20, "Manuel Fernández Baños" ***@***.***> wrote:

@Chenshupei95 send me a .tcl which raises the error and I'll try to look at it as soon as possible (too busy and not in OpenSees related tasks right now).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mfernba** [comment]
There is not attached document in your reply, or maybe, I'm not able to find it.

**Comment by Chenshupei95** [comment]
sorry about that, is there attached document in this reply?
















At 2021-11-07 23:55:00, "Manuel Fernández Baños" ***@***.***> wrote:

There is not attached document in your reply, or maybe, I'm not able to find it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mhscott** [comment]
Any updates? Re-open if needed.
