### ISSUE TITLE
No member named 'sin' or 'cos' in namespace 'std'

### ISSUE THREAD

**Issue by z-ichinohe** [OpenSees/OpenSees#981]
Hello, Mr. Petracca(@MassimoPetracca) and everyone.

I had a compile problem of std::cos or std::sin in ./SRC/material/nD/FSAM.cpp line 2698-2706 with **MacOS12** and **AppleClang13**, while It's successfully compiled by **Ubuntu** and **GCC 9.40**.

This would be solved by replacing std::cos and std::sin with cos and sin. However, it should be noted that they are only used here, while cos and sin are used in the remaining parts. Could you let me know whether they are important differences and if so let me know how to get compiling succeeded.

**Comment by jaabell** [comment]
I think this has to do with whatever math.h does for the AppleClang13 compiler. See https://stackoverflow.com/questions/10694255/cmath-vs-math-h-and-similar-c-prefixed-vs-h-extension-headers#:~:text=%5Bcmath%5D%20defines%20symbols%20in%20the,compiler%20but%20not%20with%20another.

Since the header being used is <math.h> and not <cmath> (that defines symbols in the std namespace) then the proper thing is to unqualify the use of sin and cos. 

Therefore, I've gone ahead and removed the namespace qualifications in this case. As you mention, in the rest of the code the trig functions are used withot qualifications. 

Thanks! Its good to test on other compilers.

**Comment by z-ichinohe** [comment]
Thank you so much!

**Comment by MassimoPetracca** [comment]
Thank you both @jaabell @z-ichinohe

**Comment by myk-happy** [comment]
it's useful ,thanks! @jaabell @z-ichinohe
