### ISSUE TITLE
modalProperties does not work for ndm=1

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#985]
@MassimoPetracca I tried running modalProperties on a 1D model of zero length elements, but received an error that the command only works for 2D and 3D models. Is there any reason this command cannot work for 1D models?

**Comment by mhscott** [comment]
Are the commands also able to work with ndm=2,ndf=2 and ndm=3,ndf=3, i.e., for solid models? It may not be a typical use case with non-frame models, but the calculations should still be OK, or am I missing something?

**Comment by MassimoPetracca** [comment]
@mhscott I'm sorry for the late response, but I didn't check github this last week.

> running modalProperties on a 1D model of zero length elements, but received an error that the command only works for 2D and 3D models. Is there any reason this command cannot work for 1D models?

I decided to only support ndm=2 and ndm=3 because of the way we compute the rotational component of the modal participation factors/masses. In fact, in the report generated by the command, you will always see 3 DOFs for 2D problems(2U + 1R) and 6 DOFs for 3D problems (3U+3R), even if your model has no rotational DOFs. This is because the rotational mass is computed as the "direct" rotary mass in a rotational DOF (if it exists) plus the "rigid body rotation" of the translational masses about the center of mass, as described here:
![image](https://user-images.githubusercontent.com/26160906/190339234-7cc26719-ee4d-496f-a5f8-ccb3af8e92f6.png)

So, to avoid too many if-statements I decided to restrict the usage to only ndm=2 and ndm=3. But if you want I can extend it to the ndm=1 case. In that case, I would not compute the rotational term.

> Are the commands also able to work with ndm=2,ndf=2 and ndm=3,ndf=3, i.e., for solid models? It may not be a typical use case with non-frame models, but the calculations should still be OK, or am I missing something?

Yes, it works for solid elements as well (2D and 3D). And, for the same reason explained above, you will still see the rotational components in the report of the modalProperties.

**Note**: The only issue might be in U-P solid elements: their 3rd DOF in 2D or 4th DOF in 3D might be seen as rotational DOF because I have no way to tell what physical DOF it is.

If you think this tool can be extended to other use cases please let me know.

**Comment by mhscott** [comment]
@MassimoPetracca Thanks! If you can extend the command to 1D, that would be useful for simple models of rigid shear frames built in 1D with zero length or truss elements.

**Comment by MassimoPetracca** [comment]
@mhscott here's the PR #997
