### ISSUE TITLE
ShellMITC4 creates indeterminate matrix in explicit analysis

### ISSUE THREAD

**Issue by amieloszyk** [OpenSees/OpenSees#998]
When running a case with ShellMITC4 elements for an explicit analysis, the solver fails due to an indeterminate matrix. Digging deeper, the element does not set any rotational terms in the mass matrix, which causes whole rows in the tangent matrix to be zeroed out. Bathe's description of the element in "Finite Element Procedures" seems consistent with this treatment, as the shape functions for the rotations are zeros. It appears that ShellDKGQ has a similar formulation and will have the same problem.

What is the appropriate way to add rotational mass so that I can perform an explicit calculation?

**Comment by fmckenna** [comment]
you can add mass directly to nodes using nodeMass or node command .. element contributions will also be added, so just add some rotational terms

**Comment by amieloszyk** [comment]
My concern is that is an error prone process, as hand calculating the values will lack the appropriate transformation into the isoparametric space, including potential changes to the appropriate interpretation of the values as the elements shift in the global reference frame.

For my immediate needs, it is no problem to use a hand calc, but it seems like quite the oversight in the elements' fundamental formulation that I am struggling to understand.

**Comment by MassimoPetracca** [comment]
@amieloszyk you can safely follow @fmckenna 's suggestion.
You don't need to be precise about the "direct rotary" mass (for "direct" I mean a mass term associated directly with a rotational DOF).

Typically shell elements are thin, so the "direct rotary" inertia is negligible compared to the rotational inertia of the translational mass at the nodes rotating about an axis through the element center.

The only reason why you need a "direct rotary" inertia term (on the rotational DOFs) is to avoid a singular mass matrix in explicit dynamics.
However, it cannot be a randomly small number! because if it is too small, the critical time step for explicit dynamics will go to zero.

There is a nice explanation about how to choose this value in the Abaqus' Theory Guide so that:

1. It is large enough so that the critical time step size is not governed by this "dummy" mass term
2. It is smaller than the real rotational inertia (of the translational mass at the nodes rotating about an axis through the element center)

You can find it in section 3.6.5 "Finite strain shell element formulation" -> Rotary inertia scaling for explicit dynamics
[http://130.149.89.49:2080/v6.14/books/stm/default.htm](url)

**Comment by mhscott** [comment]
@MassimoPetracca Please update the URL on the last line of your response. There's an error in the address.
